/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package example.proto;  
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class ProductionCountry extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 3106457466514985176L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"ProductionCountry\",\"namespace\":\"example.proto\",\"fields\":[{\"name\":\"iso_3166_1\",\"type\":\"string\"},{\"name\":\"name\",\"type\":\"string\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  @Deprecated public java.lang.CharSequence iso_3166_1;
  @Deprecated public java.lang.CharSequence name;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>. 
   */
  public ProductionCountry() {}

  /**
   * All-args constructor.
   */
  public ProductionCountry(java.lang.CharSequence iso_3166_1, java.lang.CharSequence name) {
    this.iso_3166_1 = iso_3166_1;
    this.name = name;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call. 
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return iso_3166_1;
    case 1: return name;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }
  // Used by DatumReader.  Applications should not call. 
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: iso_3166_1 = (java.lang.CharSequence)value$; break;
    case 1: name = (java.lang.CharSequence)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'iso_3166_1' field.
   */
  public java.lang.CharSequence getIso31661() {
    return iso_3166_1;
  }

  /**
   * Sets the value of the 'iso_3166_1' field.
   * @param value the value to set.
   */
  public void setIso31661(java.lang.CharSequence value) {
    this.iso_3166_1 = value;
  }

  /**
   * Gets the value of the 'name' field.
   */
  public java.lang.CharSequence getName() {
    return name;
  }

  /**
   * Sets the value of the 'name' field.
   * @param value the value to set.
   */
  public void setName(java.lang.CharSequence value) {
    this.name = value;
  }

  /**
   * Creates a new ProductionCountry RecordBuilder.
   * @return A new ProductionCountry RecordBuilder
   */
  public static example.proto.ProductionCountry.Builder newBuilder() {
    return new example.proto.ProductionCountry.Builder();
  }
  
  /**
   * Creates a new ProductionCountry RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new ProductionCountry RecordBuilder
   */
  public static example.proto.ProductionCountry.Builder newBuilder(example.proto.ProductionCountry.Builder other) {
    return new example.proto.ProductionCountry.Builder(other);
  }
  
  /**
   * Creates a new ProductionCountry RecordBuilder by copying an existing ProductionCountry instance.
   * @param other The existing instance to copy.
   * @return A new ProductionCountry RecordBuilder
   */
  public static example.proto.ProductionCountry.Builder newBuilder(example.proto.ProductionCountry other) {
    return new example.proto.ProductionCountry.Builder(other);
  }
  
  /**
   * RecordBuilder for ProductionCountry instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<ProductionCountry>
    implements org.apache.avro.data.RecordBuilder<ProductionCountry> {

    private java.lang.CharSequence iso_3166_1;
    private java.lang.CharSequence name;

    /** Creates a new Builder */
    private Builder() {
      super(example.proto.ProductionCountry.SCHEMA$);
    }
    
    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(example.proto.ProductionCountry.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.iso_3166_1)) {
        this.iso_3166_1 = data().deepCopy(fields()[0].schema(), other.iso_3166_1);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.name)) {
        this.name = data().deepCopy(fields()[1].schema(), other.name);
        fieldSetFlags()[1] = true;
      }
    }
    
    /**
     * Creates a Builder by copying an existing ProductionCountry instance
     * @param other The existing instance to copy.
     */
    private Builder(example.proto.ProductionCountry other) {
            super(example.proto.ProductionCountry.SCHEMA$);
      if (isValidValue(fields()[0], other.iso_3166_1)) {
        this.iso_3166_1 = data().deepCopy(fields()[0].schema(), other.iso_3166_1);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.name)) {
        this.name = data().deepCopy(fields()[1].schema(), other.name);
        fieldSetFlags()[1] = true;
      }
    }

    /**
      * Gets the value of the 'iso_3166_1' field.
      * @return The value.
      */
    public java.lang.CharSequence getIso31661() {
      return iso_3166_1;
    }

    /**
      * Sets the value of the 'iso_3166_1' field.
      * @param value The value of 'iso_3166_1'.
      * @return This builder.
      */
    public example.proto.ProductionCountry.Builder setIso31661(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.iso_3166_1 = value;
      fieldSetFlags()[0] = true;
      return this; 
    }

    /**
      * Checks whether the 'iso_3166_1' field has been set.
      * @return True if the 'iso_3166_1' field has been set, false otherwise.
      */
    public boolean hasIso31661() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'iso_3166_1' field.
      * @return This builder.
      */
    public example.proto.ProductionCountry.Builder clearIso31661() {
      iso_3166_1 = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'name' field.
      * @return The value.
      */
    public java.lang.CharSequence getName() {
      return name;
    }

    /**
      * Sets the value of the 'name' field.
      * @param value The value of 'name'.
      * @return This builder.
      */
    public example.proto.ProductionCountry.Builder setName(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.name = value;
      fieldSetFlags()[1] = true;
      return this; 
    }

    /**
      * Checks whether the 'name' field has been set.
      * @return True if the 'name' field has been set, false otherwise.
      */
    public boolean hasName() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'name' field.
      * @return This builder.
      */
    public example.proto.ProductionCountry.Builder clearName() {
      name = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    @Override
    public ProductionCountry build() {
      try {
        ProductionCountry record = new ProductionCountry();
        record.iso_3166_1 = fieldSetFlags()[0] ? this.iso_3166_1 : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.name = fieldSetFlags()[1] ? this.name : (java.lang.CharSequence) defaultValue(fields()[1]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  private static final org.apache.avro.io.DatumWriter
    WRITER$ = new org.apache.avro.specific.SpecificDatumWriter(SCHEMA$);  

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, org.apache.avro.specific.SpecificData.getEncoder(out));
  }

  private static final org.apache.avro.io.DatumReader
    READER$ = new org.apache.avro.specific.SpecificDatumReader(SCHEMA$);  

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, org.apache.avro.specific.SpecificData.getDecoder(in));
  }

}
